apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mock-openai-server.fullname" . }}-config
  labels:
    {{- include "mock-openai-server.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | nindent 4 }}
